### ISSUE TITLE
From the next feature release, `APP_KEY` will need to be set and stable

### ISSUE THREAD

**Issue by ssddanbrown** [hassio-addons/addon-bookstack#129]
:wave: 

Just wanted to give a heads-up. As of the next feature release the `APP_KEY` .env option will need to validly exist and be consistent across restarts. Ideally people will need to know to retain that value. Not sure on the depth it'll affect this project but warning early just in case. This is due to the use of encryption within the multi-factor-authentication system.

At a guess, the next feature release will arrive in about 1-2 weeks. Happy to provide more info or answer any questions if needed.

**Comment by sinclairpaul** [comment]
Thanks Dan, I believe we persist it anyway, but will double check and test on the next release.

**Comment by sinclairpaul** [comment]
Confirmed we were already persisting, also added options to display existing key on startup, and set key if necessary (in case of migration/restore) via #136
