### ISSUE TITLE
Add support debug mode

### ISSUE THREAD

**Issue by kamontat** [hassio-addons/addon-bookstack#14]
# Problem/Motivation

BookStack has debugging mode (https://www.bookstackapp.com/docs/admin/debugging/). It will be better if we can enable it in add-on page

## Expected behavior

> Enable debug mode

## Actual behavior

> Cannot

<blockquote><div><img src="/images/favicon-32x32.png" height="14"> BookStack</div><div><strong><a href="https://bookstackapp.com/docs/admin/debugging/"> Debugging Errors ·  BookStack</a></strong></div></blockquote>

**Comment by sinclairpaul** [comment]
I'll link it to the log_level config (set to debug or trace), in the next release
