### ISSUE TITLE
Unable to log into Bookstack in Edge or Chrome

### ISSUE THREAD

**Issue by jane-t** [hassio-addons/addon-bookstack#146]
# Problem/Motivation

If trying to log in on Edge or Chrome, after entering the User ID and Password 419 Page Expired is displayed.
I do not use https on my internal Home Assistant machine, I am not sure if this may be the route of the problem,

## Expected behavior

To be able to log in

## Actual behavior

Error 419 displayed

## Steps to reproduce

Open Edge or Chrome where Bookstack is not logged in and click on Log in and try and log in.

The log seems to be working fine in Firefox even with the enhanced protection turned on.

**Comment by sinclairpaul** [comment]
The only time I have seen this was around issues with the cookie used for auth.

Would suggest if it works in one browser and not another it would likely be some kind of cookie/cache issue.
