### ISSUE TITLE
Add optional PDF rendering

### ISSUE THREAD

**Issue by kamontat** [hassio-addons/addon-bookstack#15]
# Problem/Motivation

It will be nice if we can choose pdf render from add-on config page

ref: https://www.bookstackapp.com/docs/admin/pdf-rendering/

## Expected behavior

> Changes PDF rendering

## Actual behavior

> Cannot

<blockquote><div><img src="/images/favicon-32x32.png" height="14"> BookStack</div><div><strong><a href="https://bookstackapp.com/docs/admin/pdf-rendering/"> PDF Rendering ·  BookStack</a></strong></div></blockquote>

**Comment by sinclairpaul** [comment]
I'll just change it to use wkhtmltopdf in the next release, don't see the need to make it optional if it performs better for minimal size increase.

**Comment by sinclairpaul** [comment]
From testing the Alpine package doesn't work correctly for me, so will hold off on this for now.

**Comment by kamontat** [comment]
I tested for me is working.. how you install `wkhtmltopdf` command?

**Comment by sinclairpaul** [comment]
PR's are always welcome, at the moment I don't see this working under Alpine

**Comment by kamontat** [comment]
I not sure is it gonna work or not, I never run in local but I create PR so you might try #16

**Comment by sinclairpaul** [comment]
This still isn't working correctly for me, so will close it out for now.
