### ISSUE TITLE
reinstalled HA forgot email and password what to do?

### ISSUE THREAD

**Issue by edwardtich1** [hassio-addons/addon-bookstack#159]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
I'm sure you can get a book on Amazon on memory improvement, or use a password manager.

**Comment by ssddanbrown** [comment]
Upon the above advice, BookStack does have a command to create a new admin user which can be useful in such scenarios:
https://www.bookstackapp.com/docs/admin/commands/

I'm not familiar enough though with this environment to know the methods, possibilities or each of running such commands.
