### ISSUE TITLE
Update to BookStack v21.11.1

### ISSUE THREAD

**Issue by dm82m** [hassio-addons/addon-bookstack#160]
# Problem/Motivation

I want to use the new features.

## Expected behavior

Using the new version BookStack v21.11.1

## Actual behavior

-

## Steps to reproduce

-

## Proposed changes

-

**Comment by frenck** [comment]
This is not an issue but a feature request. Therefore closing it.

**Comment by dm82m** [comment]
@sinclairpaul thanks for the fast upgrade. One question: I checked the last upgrade commit and did the same but I missed to upgrade base image and dependencies.
Can you tell me where you found that this is needed? Just asking so that I can maybe take care of the next upgrade.
Second question: how could I test that change in my local environment, so that I ensure that it is tested before applying the pull request.

**Comment by sinclairpaul** [comment]
You are better discussing these things on Discord, which is probably the best thing to do anyway before contributing.

You need to watch the base image releases, and update when needed.  You can test locally using "docker build" commands, to build the container and get more logging than building on the Supervisor provides.  Also I would suggest looking at the addon Development documentation to understand the structure.

The key thing to me is not just bumping versions (we could essentially have a bot do that), but there needs to be some level of testing afterwards to see what the level of impact is.
