### ISSUE TITLE
Can't upload image or files

### ISSUE THREAD

**Issue by hase091** [hassio-addons/addon-bookstack#171]
Hello all,

# Problem/Motivation
I'm not able to upload any image or file inside a page.
The file size, name or type seems to not metter.

## Actual behavior
I've tried both upload directly on a page and using the side bar but the problem is the same:

> (Log)
2022/01/22 09:40:32 [error] 635#635: *41 FastCGI sent in stderr: "PHP message: PHP Warning:  File upload error - unable to create a temporary file in Unknown on line 0" while reading response header from upstream, client: 192.168.1.20, server: a0d7b954-bookstack, request: "POST /attachments/upload?uploaded_to=2 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "192.168.1.106:2665", referrer: "http://192.168.1.106:2665/books/blender/page/dividere-due-oggetti/edit"

## Tries
After logging into the container I've tried to change the permissions for the path **/data/bookstack/uploads** (_777 for testing purpose_) but the error still occurs.

Can someone please support this request?
Thanks.

**Comment by kds69** [comment]
same here v1.0.1 but on hassio
