### ISSUE TITLE
Can't send email to user at creation or test mail sending :

### ISSUE THREAD

**Issue by williamhelle** [hassio-addons/addon-bookstack#182]
# Problem/Motivation
Send email or test-email

## Expected behavior
He can't

## Actual behavior
Error thrown when sending a test email: Expected response code 354 but got code "503", with message "503 RCPT command expected "

<html>
<body>

User | Event | Related Item or Detail | IP Address | Activity Date
-- | -- | -- | -- | --
Admin | maintenance_action_run | send-test-email | IP ADDRESS | 2022-05-24 08:04:20
Admin | maintenance_action_run | send-test-email | IP ADDRESS | 2022-05-24 08:04:14
Admin | maintenance_action_run | send-test-email | IP ADDRESS | 2022-05-24 08:03:55

</body>
</html>

## Steps to reproduce
Send email or test-email

## Proposed changes
Fix/Make email services, Sign-in a mail to the app to send password on mail with it.User	[Event](https://homeassistant.local:2665/settings/audit?order=asc&sort=key)	Related Item or Detail	IP Address	[Activity Date](https://homeassistant.local:2665/settings/audit?order=asc&sort=created_at)
[Admin](https://homeassistant.local:2665/settings/users/1)
Admin
maintenance_action_run	
send-test-email
192.168.1.22	2022-05-24 08:04:20
[Admin](https://homeassistant.local:2665/settings/users/1)
Admin
maintenance_action_run	
send-test-email
192.168.1.22	2022-05-24 08:04:14
[Admin](https://homeassistant.local:2665/settings/users/1)
Admin
maintenance_action_run	
send-test-email
192.168.1.22	2022-05-24 08:03:55

**Comment by sinclairpaul** [comment]
You are receiving a response from your SMTP server, so it is likely configuration.

Please validate your settings around authentication with your SMTP provider.
