### ISSUE TITLE
File path <path> could not be uploaded to. Ensure it is writable to the server.

### ISSUE THREAD

**Issue by worf-nm** [hassio-addons/addon-bookstack#19]
# Problem/Motivation

Unable to upload any images

## Expected behavior

To be able to upload images

## Actual behavior

An Error Occurred
File path /uploads/images/cover_book/2020-09/filename could not be uploaded to. Ensure it is writable to the server.

## Steps to reproduce

try to upload an image

**Comment by worf-nm** [comment]
This appears to be the same as [#18](https://github.com/hassio-addons/addon-bookstack/issues/18), but I decided not to use another man's topic.
The logs show absolutely the same in either info or trace mode:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] bookstack: applying... 
[fix-attrs.d] bookstack: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Bookstack
 Simple & Free Wiki Software
-----------------------------------------------------------
 Add-on version: 0.4.4
 You are running the latest version of this add-on.
 System: HassOS 4.12  (amd64 / qemux86-64)
 Home Assistant Core: 0.114.4
 Home Assistant Supervisor: 240
...
[07/Sep/2020:18:52:25 +0300] 500 192.168.10.2(172.30.32.1) POST /books/unifi-controller-e46 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0)

I also tried using the workaround from [#18](https://github.com/hassio-addons/addon-bookstack/issues/18) by granting 774 recursively to /data/bookstack/uploads, but to no avail.

What's worth mentioning is that I had the addon running on a different system and restored it to the current installation just recently. Besides unable to upload, all previous images are still present, but not displayed.

Thank you!

**Comment by sinclairpaul** [comment]
> What's worth mentioning is that I had the addon running on a different system and restored it to the current installation just recently. Besides unable to upload, all previous images are still present, but not displayed.

Thanks, I believe this may also be the same cause for the previous issue created.  I believe its to do with the User ID mapping in Docker.

I will push a fix shortly that should help resolve the issue.

**Comment by worf-nm** [comment]
Thanks @sinclairpaul!
