### ISSUE TITLE
# Problem/Motivation

### ISSUE THREAD

**Issue by LordNex** [hassio-addons/addon-bookstack#198]
# Problem/Motivation
Send email or test-email

## Expected behavior
He can't

## Actual behavior
Error thrown when sending a test email: Expected response code 354 but got code "503", with message "503 RCPT command expected "

<html>
<body>

User | Event | Related Item or Detail | IP Address | Activity Date
-- | -- | -- | -- | --
Admin | maintenance_action_run | send-test-email | IP ADDRESS | 2022-05-24 08:04:20
Admin | maintenance_action_run | send-test-email | IP ADDRESS | 2022-05-24 08:04:14
Admin | maintenance_action_run | send-test-email | IP ADDRESS | 2022-05-24 08:03:55

</body>
</html>

## Steps to reproduce
Send email or test-email

## Proposed changes
Fix/Make email services, Sign-in a mail to the app to send password on mail with it.User	[Event](https://homeassistant.local:2665/settings/audit?order=asc&sort=key)	Related Item or Detail	IP Address	[Activity Date](https://homeassistant.local:2665/settings/audit?order=asc&sort=created_at)
[Admin](https://homeassistant.local:2665/settings/users/1)
Admin
maintenance_action_run	
send-test-email
192.168.1.22	2022-05-24 08:04:20
[Admin](https://homeassistant.local:2665/settings/users/1)
Admin
maintenance_action_run	
send-test-email
192.168.1.22	2022-05-24 08:04:14
[Admin](https://homeassistant.local:2665/settings/users/1)
Admin
maintenance_action_run	
send-test-email
192.168.1.22	2022-05-24 08:03:55

__Originally posted by @williamhelle in https://github.com/hassio-addons/addon-bookstack/issues/182__

**Comment by LordNex** [comment]
Reopened as I'm having the same issue. Please see [Issue 3877](https://github.com/BookStackApp/BookStack/issues/3877#issue-1465643083)

**Comment by ssddanbrown** [comment]
Based upon your issue in BookStackApp/BookStack#3877 you have not performed any SMTP configuration.

I do not run this addon myself, so have not tested this, but [looking at the docs](https://github.com/hassio-addons/addon-bookstack/blob/v1.3.1/bookstack/DOCS.md) you can pass env options to BookStack via the `envvars` option in the addon configuration.

The available BookStack Mail & SMTP options [can be seen here](https://github.com/BookStackApp/BookStack/blob/40a1377c0bfbc059f619c5c17802622c3b16d05a/.env.example.complete#L68-L81). Should just be a case of defining these via the `envars`.  For example, to set the `MAIL_HOST` and `MAIL_PORT` I'd update the config with:

```yaml
envvars:
  - name: MAIL_HOST
    value: smtp.pigeonmail.org
  - name: MAIL_PORT
    value: 587
```

**Comment by LordNex** [comment]
Yea the problem there is that this is packaged as an addon for Home Assistant so I don't have control over those settings. I'm pretty sure it will need to be the person who wrote the addin that corrects this but for some reason it defaulted to me opening an issue under the main application. 

What would be preferable would be to include these as variables in the Configuration Tab of the add on but currently there is nothing. And I really don't want to go messing around with the docker container as Home Assistant manages that itself with the Supervisor.

**Comment by ssddanbrown** [comment]
> so I don't have control over those settings

On the configuration tab for the BookStack addon, click the three dots towards the top-right then select "Edit in YAML".
You should then see a `envvars` option there.

> What would be preferable would be to include these as variables in the Configuration Tab of the add on but currently there is nothing. 

I'm not sure what abilities homeassistant addon authors have in terms of exposing options as UI controls, but I can understand why this might not be done, since the env options provided by BookStack are quite vast and can often change/expand. Adding hard-coded option-specific controls could add maintenance debt for the addon.

**Comment by LordNex** [comment]
> > so I don't have control over those settings
> 
> 
> 
> On the configuration tab for the BookStack addon, click the three dots towards the top-right then select "Edit in YAML".
> 
> You should then see a `envvars` option there.
> 
> 
> 
> > What would be preferable would be to include these as variables in the Configuration Tab of the add on but currently there is nothing. 
> 
> 
> 
> I'm not sure what abilities homeassistant addon authors have in terms of exposing options as UI controls, but I can understand why this might not be done, since the env options provided by BookStack are quite vast and can often change/expand. Adding hard-coded option-specific controls could add maintenance debt for the addon. 

Ok I've found the settings but it's giving an error no matter how I try and save it. 

![image](https://user-images.githubusercontent.com/9270948/204310134-2423f0f0-22bc-4db0-b3bd-454e94431ad1.jpeg)

![image](https://user-images.githubusercontent.com/9270948/204310184-6a028070-6059-4a80-8b20-fadec087a741.jpeg)
