### ISSUE TITLE
Database choices

### ISSUE THREAD

**Issue by roybosch** [hassio-addons/addon-bookstack#20]
# Problem/Motivation

> I'd like to use Bookstack within my HA instance. I noticed that it's not possible to use Bookstack without MariaDB. I'm using MariaDB, but I'm not backing it up because I don't care about keeping history of sensors. It's different with information stored in bookstack of course.

It would be nice to have (an option for) a dedicated DB implemented into this Bookstack addon.

## Expected behavior

> I'd like not to be dependend on the HA database.

## Actual behavior

> I'm dependend on the HA database

## Steps to reproduce

> null

## Proposed changes

> Adding an option to use a dedicated DB that's backed up using the addon snapshot feature.

**Comment by frenck** [comment]
We are not implementing a database server inside the add-on itself. This is highly inefficient for smaller platforms (like a raspberry Pi), besides, it adds a lot of maintenance overhead and unneeded complexity.
