### ISSUE TITLE
Unreachable through Nabu Casa

### ISSUE THREAD

**Issue by kayloehmann** [hassio-addons/addon-bookstack#21]
# Problem/Motivation
Try to access Bookstack through remote feature of nabu casa.

## Expected behavior
access Bookstack through remote feature of nabu casa.

## Actual behavior
Timeout happens

## Steps to reproduce
Try to run Bookstack through remote nabu casa access.

## Proposed changes
Enable Remote Access for Bockstack through Nabu Casa.

Thanks! Kay.

**Comment by frenck** [comment]
This is correct. This add-on does not have Ingress support and will not be able to support Ingress, unfortunately.

Add-on that do support Ingress show the following badge on their add-on page in the Supervisor:

![image](https://user-images.githubusercontent.com/195327/94410738-ff3f3300-0177-11eb-9191-0e7e56599138.png)


Lastly, the documentation of the add-on documents this:

![image](https://user-images.githubusercontent.com/195327/94410826-1a11a780-0178-11eb-8c4b-16dbcc9b6ba3.png)

**Comment by kayloehmann** [comment]
Thanks for the explanation.
