### ISSUE TITLE
Clarify documentation concerning environment variables

### ISSUE THREAD

**Issue by blizzardfinnegan** [hassio-addons/addon-bookstack#211]
# Problem/Motivation

> Environment variable declaration in the documentation is currently unclear, as it uses real values, rather than more clearly marked example values. It is also unclear to new users that multiple environment variables can be set. 

## Proposed changes

> Modifying the documentation to include multiple explicitly-stated-as-example variables would alleviate this issue.

**Comment by sinclairpaul** [comment]
Personally I don't agree, however rather than opening an issue, please feel free to contribute, as creating a PR for documentation is quite straightforward.
