### ISSUE TITLE
Changing tinyMCE menu options

### ISSUE THREAD

**Issue by kiwipaulrob** [hassio-addons/addon-bookstack#22]
# Problem/Motivation

I want to save YAML examples so need a 
`<code> </code> `
editor option
## Expected behavior

There is a code button on tinyMCE button ribbon

## Actual behavior

Not implemented

## Steps to reproduce

See above

## Proposed changes

TinyMCE options include a code button.

https://www.tiny.cloud/docs-3x/reference/buttons/

I appreciate that your usecase is a simple wiki but given its an addon to Homeassistant it makes sense to allow YAML code to be saved with correct spacing.

Thanks for great work and Merry Christmas!

**Comment by sinclairpaul** [comment]
The addon wraps the existing software, not sure of the reference linked, but the request would need to be made at source.
