### ISSUE TITLE
Running via HTTPS

### ISSUE THREAD

**Issue by tstill88** [hassio-addons/addon-bookstack#271]
Im using NGNIX with an SSL cert so i can access this remotely, however there is an issue with the css when viewed with https.

There is a closed issue on the bookstack github with a fix, are you able to implement this into the HA Add-on?

https://github.com/BookStackApp/BookStack/issues/3328

**Comment by ssddanbrown** [comment]
The main "fix" there was to set the BookStack "APP_URL" option to align with the desired browser URL, so via the addon configuration, something like this:

```yaml
envvars:
  - name: APP_URL
    value: https://<your_bookstack_url>
```

I must admit I'm not really familiar with the hassio setup though so not sure how this may affect usage within homeassistant itself, or how you might run the BookStack [command to update URLs](https://www.bookstackapp.com/docs/admin/commands/#update-system-url) of existing content (if needed).
