### ISSUE TITLE
How do you add your wiki to Home assistant in a way users can access it?

### ISSUE THREAD

**Issue by domarseneault** [hassio-addons/addon-bookstack#278]
# Problem/Motivation
I can only seem to access the ui of the wiki through the addon redirectign me to the url in a new tab. I'm trying to get it to show in home assistnat somehow

## Expected behavior

the web ui should appear on the left side bar in the same way the grocy app does would be my assumption

I'm not sure if I'm just missing a config option or feature-- apologies if I am

**Comment by sinclairpaul** [comment]
Not all applications support that option, this is one of them.
