### ISSUE TITLE
Keep up to date

### ISSUE THREAD

**Issue by Torpedro1978** [hassio-addons/addon-bookstack#279]
# Problem/Motivation
The version is very old compared to https://github.com/BookStackApp/BookStack/releases.
Can you please update to the latest version.

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by tjorim** [comment]
Last update was 2 months ago, currently running bookstack version 23.08.3. Nonetheless, this is a feature request, not an issue so closing it.
