### ISSUE TITLE
MariaDB not installed by default 

### ISSUE THREAD

**Issue by mbalsam** [hassio-addons/addon-bookstack#292]
# Problem/Motivation

MariaDB is not installed by default 
Event after I installed MariaDB it did not work

## Actual behavior
cont-init: info: running /etc/cont-init.d/bookstack.sh
[12:01:34] FATAL: Local database access should be provided by the MariaDB addon
[12:01:34] FATAL: Please ensure it is installed and started
> (What actually happened)

**Comment by frenck** [comment]
This is not something this add-on can do anything about. It gets its data from the Supervisor and is thus limited by the response it gives.

According to the supervisor it doesn't exists or isn't running. From this add-ons perspective, there is nothing we can do about that.

../Frenck
