### ISSUE TITLE
Please add php7-ldap support

### ISSUE THREAD

**Issue by rwesterflan** [hassio-addons/addon-bookstack#52]
# Problem/Motivation

> Most applications in my homelab authenticate via LDAP. I can enable it for Bookstack in the envvars, but the module is missing.

## Expected behavior

> Enable LDAP for logins

## Actual behavior

> Bookstacks throws an error that PHP-LDAP extension is not installed

## Proposed changes

> So far, running 'apk add php7-ldap' seems to work, but that's not ideal with updating

**Comment by sinclairpaul** [comment]
If its just the dependency that's needed, I will add it in the next release.

**Comment by rwesterflan** [comment]
Thank you very much!
