### ISSUE TITLE
Using ".js" in the page title breaks nginx

### ISSUE THREAD

**Issue by Salvora** [hassio-addons/addon-bookstack#63]
# Problem/Motivation

 if you create a new page with a title ending with .js, this breaks the nginx and renders the page inaccessible with "404 Not Found" errors just for this page.
The same issue also raised for the BookStack itself but apparently the problem is not the internal webserver.

https://github.com/BookStackApp/BookStack/issues/2645

## Expected behavior

Page should open normally/

## Actual behavior

404 Error

## Steps to reproduce
1. Go to a book
2. Create a blank page
3. title it with something like "Node.js" (without quotes)

## Proposed changes

Fix for webserver

**Comment by sinclairpaul** [comment]
Will be fixed next release, it's to do with the cache rules in nginx, I'll remove them as it's not as if the site hosts 100's of users :)

**Comment by sinclairpaul** [comment]
Fixed in v0.8.5, will be available shortly, you can refresh the addon store manually to see it.

**Comment by Salvora** [comment]
Thanks, it is fixed now. It was an obscure bug though. I don't believe other than me someone would like to name something with node.js (:
