### ISSUE TITLE
Addon missing? 

### ISSUE THREAD

**Issue by Jeroendeeerste** [hassio-addons/addon-bookstack#9]
I would love to use this addon, but it seems absent from the addon store, and is not mentioned on the website (https://addons.community/). I do use a lot of other community addons without issue, and have added the repository. Am i missing something? 

<blockquote><img src="assets/images/favicon.png" width="48" align="right"><div><strong><a href="https://addons.community/">Community Hass.io Add-ons for Home Assistant</a></strong></div><div>The primary goal of this project is to provide you (as a Hass.io / Home Assistant user) with additional, high quality, add-ons that allow you to take your automated home to the next level.</div></blockquote>

**Comment by frenck** [comment]
It is not missing, it is not released yet.
